create database ANARI
default character set utf8
default collate utf8_general_ci;
-- CRIANDO TABELA DE USUÁRIOS DO SISTEMA
DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO
	(
	NOME_USUARIO     VARCHAR (50),
	CARTAO_USUARIO   INT,
	CARGO_USUARIO    VARCHAR (30),
	SENHA_USUARIO	 INT	DEFAULT 6,
    NIVEL_USUARIO    INT NOT NULL ,
    
     PRIMARY KEY (CARTAO_USUARIO)
     )
    DEFAULT CHARSET= utf8;
    

	

INSERT INTO     USUARIO
	( 
	   NOME_USUARIO, CARTAO_USUARIO, CARGO_USUARIO, SENHA_USUARIO, NIVEL_USUARIO 
	)
VALUES
	('ALEXANDRE CURA','1020','LIDER ALMOXARIFE', '010102','2'),
	('ISANETE PERUZZI', '1120','GERENTE GERAL', '010103','2'),
	('NICOLAS LIRA', '1221','SUPERVISOR', '010104' , '1'),
	('REINALDO BARBOSA', '1322','COORDENADOR', '010105','1'),
	('VICTOR WILLIAMS STAFUSA', '1000','DIRETOR PROPIETÁRIO', '100110','2');

/***************************************************************************************/

-- CRIANDO TABELA DOS FORNECEDORES
DROP TABLE  FORNECEDOR;
CREATE TABLE FORNECEDOR
	(
    COD_FORNECEDOR INT NOT NULL AUTO_INCREMENT,
	NOME_FORNECEDOR     VARCHAR (30),   
	CNPJ_FORNECEDOR    BIGINT,
	ENDERECO_FORNECEDOR VARCHAR(50),
	UDF_FORNECEDOR		CHAR(2),

		PRIMARY KEY (COD_FORNECEDOR)   
	)     DEFAULT CHARSET= utf8;
    
INSERT INTO FORNECEDOR
	(
	NOME_FORNECEDOR, CNPJ_FORNECEDOR, ENDERECO_FORNECEDOR, UDF_FORNECEDOR
	)

VALUES
	('TNG', 24599200011723, 'AV. N. SRA. DAS GRAÇAS, 413', 'SP' ),
	('MOFFICER',  24599578631635, 'AV. PRESIDENTE WILSON,3743', 'SP' ),
	('MORMAII',  24599578614785, 'RUA PASCHOAL GASTOLDO 386', 'SP' ),
	('HUGO BOSS',  74589578613545, 'RUA SAO QUIRINO, 930', 'SP' ),
	('OAKLEY',  21499578471258, 'RUA PAULO FRANCO, 305', 'SC' ),
	('LOST',  5478963254785, 'RUA RIO TAMANDUATEI, 93', 'RS' ),
	('HERING',  24599557896348, 'RUA CIPRIANO BARATA, 523', 'PR' ),
	('SHOWLDER',  35278963414785, 'VIA ANCHIETA, 520', 'SP' ),
	('FARM',  24558741236985, 'RUA PASCHOAL GASTOLDO 386', 'RJ' ),
	('SIMULAÇÃO',  25632178965425, 'RUA MUNIS DE SOUZA, 476', 'SC' ),
	('POIM',  478569874128, 'RUA VENANCIO,747', 'SP' ),
	('PULLA BULLA',  245994785326785, 'AV.VAUTIER 93/111', 'PR' ),
	('RESERVA',  245994757413652, 'RUA HUMBERTO MATERAZO 2535', 'PR' );

/***************************************************************************************/

-- CRIANDO TABELA DE PRODUTOS
DROP TABLE IF EXISTS PRODUTO;
CREATE TABLE PRODUTO
	(
	COD_PRODUTO			INT NOT NULL AUTO_INCREMENT,
	CATEGORIA_PRODUTO		CHAR(20)NOT NULL,
	TIPO_PRODUTO			CHAR(20) NULL,	
	TAMANHO_PRODUTO			VARCHAR(5),
	GENERO_PRODUTO			ENUM ('M' ,'F'),
	DEPARTAMENTO_PRODUTO	CHAR(8),
	COD_FORNECEDOR		INT,
	QUANTIDADE_PRODUTO      INT NOT NULL,	
	PRIMARY KEY(COD_PRODUTO	),
    FOREIGN KEY (COD_FORNECEDOR)    REFERENCES FORNECEDOR	(COD_FORNECEDOR )
	)  DEFAULT CHARSET= utf8;

INSERT INTO PRODUTO
	(
	 CATEGORIA_PRODUTO, TIPO_PRODUTO, TAMANHO_PRODUTO,  GENERO_PRODUTO, 
    DEPARTAMENTO_PRODUTO, COD_FORNECEDOR, QUANTIDADE_PRODUTO
	)

VALUES
	('CALÇA','JEANS', '40', 'M', 'ADULTO', 1, 20),    
	('CALÇA', 'JEANS','42', 'm', 'ADULTO', 1, 20),
	('CALÇA', 'JEANS','38', 'M', 'ADULTO', 1, 20),
	('CALÇA', 'JEANS','48', 'M', 'ADULTO', 1, 20),
	('CALÇA','JEANS', '44', 'M', 'ADULTO', 1, 20),    
	('CALÇA','JEANS', '26', 'M', 'INFANTIL', 1, 20),
	('CALÇA','JEANS', '28', 'M', 'INFANTIL', 1, 20),
	('CALÇA', 'JEANS','24', 'M', 'INFANTIL', 1, 20),
	('CALÇA','SARJA', '26', 'M', 'INFANTIL', 1, 20),
	('CALÇA','SARJA', '28', 'M', 'INFANTIL', 1, 20),
	('CALÇA','SARJA', '24', 'M', 'INFANTIL', 1, 20),
	('CALÇA','LINHO', '26', 'M', 'INFANTIL', 1, 20),
	('CALÇA','LINHO', '28', 'M', 'INFANTIL', 1, 20),
	('CALÇA','LINHO', '24', 'M', 'INFANTIL', 1, 20),
	('CALÇA','SARJA', '40', 'M', 'ADULTO', 2, 20),
	('CALÇA', 'SARJA','42', 'M', 'ADULTO', 2, 20),
	('CALÇA', 'SARJA','38', 'M', 'ADULTO', 2, 20),
	('CALÇA', 'SARJA','48', 'M', 'ADULTO', 2, 20),
	('CALÇA','SARJA', '44', 'M', 'ADULTO', 2, 0),
	('CALÇA','LINHO', '40', 'M', 'ADULTO', 2, 20),
	('CALÇA', 'LINHO','42', 'M', 'ADULTO',2 , 20),
	('CALÇA', 'LINHO','38', 'M', 'ADULTO',2 , 20),
	('CALÇA', 'LINHO','48', 'M', 'ADULTO',2 , 20),
	('CALÇA','LINHO', '44', 'M', 'ADULTO',2 , 20),
	('CALÇA', 'SARJA', '34', 'F', 'ADULTO', 11, 20),
	('CALÇA', 'SARJA', '36', 'F', 'ADULTO', 11, 20),
	('CALÇA', 'SARJA', '38', 'F', 'ADULTO', 11, 20),
	('CALÇA', 'SARJA', '40', 'F', 'ADULTO', 11, 20),
	('CALÇA', 'SARJA', '42', 'F', 'ADULTO', 2, 20),
	('CALÇA', 'LINHO', '34', 'F', 'ADULTO',2 , 20),
	('CALÇA', 'LINHO', '36', 'F', 'ADULTO',2 , 20),
	('CALÇA', 'LINHO', '38', 'F', 'ADULTO',2 , 20),
	('CALÇA', 'LINHO', '40', 'F', 'ADULTO',2 , 20),
	('CALÇA', 'LINHO', '42', 'F', 'ADULTO',2 , 20),
	('CALÇA', 'JEANS', '34', 'F', 'ADULTO',2 , 20),
	('CALÇA', 'JEANS', '36', 'F', 'ADULTO',2 , 20),
	('CALÇA', 'JEANS', '38', 'F', 'ADULTO',2 , 20),
	('CALÇA', 'JEANS', '40', 'F', 'ADULTO',2 , 20),
	('CALÇA', 'JEANS', '42', 'F', 'ADULTO',2 , 20),
	('CONJUNTO', 'MOLETOM', 'P', 'F', 'ADULTO',3 , 20),
	('CONJUNTO', 'MOLETOM', 'M', 'F', 'ADULTO', 3 , 20),
	('CONJUNTO', 'MOLETOM', 'G', 'F', 'ADULTO',3 , 20),
	('CONJUNTO', 'MOLETOM', 'P', 'M', 'ADULTO',3 , 20),
	('CONJUNTO', 'MOLETOM', 'M', 'M', 'ADULTO',3 , 20),
	('CONJUNTO', 'MOLETOM', 'G', 'M', 'ADULTO', 3, 20),
	('CONJUNTO', 'MOLETOM', 'P', 'F', 'INFANTIL', 3, 20),
	('CONJUNTO', 'MOLETOM', 'M', 'F', 'INFANTIL', 3, 20),
	('CONJUNTO', 'MOLETOM', 'G', 'F', 'INFANTIL',3 , 20),
	('CONJUNTO', 'MOLETOM', 'P', 'M', 'INFANTIL',3 , 20),
	('CONJUNTO', 'MOLETOM', 'M', 'M', 'INFANTIL',3 , 20),
	('CONJUNTO', 'MOLETOM', 'G', 'M', 'INFANTIL',3 , 20),
	('CONJUNTO', 'ALGODAO', 'P', 'M', 'INFANTIL',11 , 20),
	('CONJUNTO', 'ALGODAO', 'M', 'M', 'INFANTIL',11, 20),
	('CONJUNTO', 'ALGODAO', 'G', 'M', 'INFANTIL',11, 20),
	('CONJUNTO', 'ALGODAO', 'P', 'M', 'INFANTIL',12 , 20),
	('CONJUNTO', 'ALGODAO', 'M', 'M', 'INFANTIL',12 , 20),
	('CONJUNTO', 'ALGODAO', 'G', 'M', 'INFANTIL',12 , 20),
	('SAIA SOCIAL', 'SARJA', '34', 'F', 'ADULTO',2 , 20),
	('SAIA SOCIAL', 'SARJA', '36', 'F', 'ADULTO',1 , 20),
	('SAIA SOCIAL', 'SARJA', '38', 'F', 'ADULTO',2, 20),
	('SAIA SOCIAL', 'SARJA', '40', 'F', 'ADULTO',1 , 20),
	('SAIA SOCIAL', 'SARJA', '42', 'F', 'ADULTO',2 , 20),
	('SAIA SOCIAL', 'LINHO', '34', 'F', 'ADULTO',2 , 20),
	('SAIA SOCIAL', 'LINHO', '36', 'F', 'ADULTO', 2, 20),
	('SAIA SOCIAL', 'LINHO', '38', 'F', 'ADULTO',2 , 20),
	('SAIA SOCIAL', 'LINHO', '40', 'F', 'ADULTO',2 , 20),
	('SAIA SOCIAL', 'LINHO', '42', 'F', 'ADULTO',2 , 20),
	('SAIA SOCIAL', 'JEANS', '34', 'F', 'ADULTO',2 , 20),
	('SAIA SOCIAL', 'JEANS', '36', 'F', 'ADULTO',2 , 20),
	('SAIA SOCIAL', 'JEANS', '38', 'F', 'ADULTO',2 , 20),
	('SAIA SOCIAL', 'JEANS', '40', 'F', 'ADULTO',2 , 20),
	('SAIA SOCIAL', 'JEANS', '42', 'F', 'ADULTO',2 , 20),
	('MINI-SAIA', 'JEANS', '34', 'F', 'ADULTO',8 , 20),
	('MINI-SAIA', 'JEANS', '36', 'F', 'ADULTO',8 , 20),
	('MINI-SAIA', 'JEANS', '38', 'F', 'ADULTO',8 , 20),
	('MINI-SAIA', 'JEANS', '40', 'F', 'ADULTO',8 , 20),
	('MINI-SAIA', 'JEANS', '42', 'F', 'ADULTO',8 , 20),
	('MINI-SAIA', 'SARJA', '34', 'F', 'ADULTO',8 , 20),
	('MINI-SAIA', 'SARJA', '36', 'F', 'ADULTO',8 , 20),
	('MINI-SAIA', 'SARJA', '38', 'F', 'ADULTO',8 , 20),
	('MINI-SAIA', 'SARJA', '40', 'F', 'ADULTO',8 , 20),
	('MINI-SAIA', 'SARJA', '42', 'F', 'ADULTO',8 , 20),
	( 'BERMUDA', 'SARJA', '46', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'SARJA', '44', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'SARJA', '38', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'SARJA', '40', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'SARJA', '42', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'LINHO', '44', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'LINHO', '46', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'LINHO', '38', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'LINHO', '40', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'LINHO', '42', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'JEANS', '44', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'JEANS', '46', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'JEANS', '38', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'JEANS', '40', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'JEANS', '42', 'M', 'ADULTO',4 , 20),
	( 'BERMUDA', 'JEANS', 'P', 'M', 'INFANTIL',4 , 20),
	( 'BERMUDA', 'JEANS', 'M', 'M', 'INFANTIL',4 , 20),
	( 'BERMUDA', 'JEANS', 'G', 'M', 'INFANTIL',4 , 20),
	( 'BERMUDA', 'LINHO', 'P', 'M', 'INFANTIL',4 , 20),
	( 'BERMUDA', 'LINHO', 'M', 'M', 'INFANTIL',4 , 20),
	( 'BERMUDA', 'LINHO', 'G', 'M', 'INFANTIL',4 , 20),
	( 'BERMUDA', 'SARJA', 'P', 'M', 'INFANTIL',4 , 20),
	( 'BERMUDA', 'SARJA', 'M', 'M', 'INFANTIL',4 , 20),
	( 'BERMUDA', 'SARJA', 'G', 'M', 'INFANTIL',4 , 20),    
	( 'BERMUDA', 'BANHO', '44', 'M', 'ADULTO',5 , 20),
	( 'BERMUDA', 'BANHO', '46', 'M', 'ADULTO',5 , 20),
	( 'BERMUDA', 'BANHO', '38', 'M', 'ADULTO',5 , 20),
	( 'BERMUDA', 'BANHO', '40', 'M', 'ADULTO',5 , 20),
	( 'BERMUDA', 'BANHO', '42', 'M', 'ADULTO',5 , 20),
	( 'BERMUDA', 'BANHO', '44', 'M', 'ADULTO',5 , 20),
	( 'BERMUDA', 'BANHO', '46', 'M', 'ADULTO',6 , 20),
	( 'BERMUDA', 'BANHO', '38', 'M', 'ADULTO',6 , 20),
	( 'BERMUDA', 'BANHO', '40', 'M', 'ADULTO',6 , 20),
	( 'BERMUDA', 'BANHO', '42', 'M', 'ADULTO',6 , 20),
	('CAMISETA LISA', 'GOLA V', 'P', 'M', 'ADULTO',7 , 20),
	('CAMISETA LISA', 'GOLA V', 'M', 'M', 'ADULTO',7 , 20),
	('CAMISETA LISA', 'GOLA V', 'G', 'M', 'ADULTO',7 , 20),
	('CAMISETA LISA', 'GOLA CARECA', 'P', 'M', 'ADULTO', 7, 20),
	('CAMISETA LISA', 'GOLA CARECA', 'M', 'M', 'ADULTO',7 , 20),
	('CAMISETA LISA', 'GOLA CARECA', 'G', 'M', 'ADULTO',7 , 20),
	('CAMISETA ESTAMPADA', 'GOLA V', 'P', 'M', 'ADULTO',13 , 20),
	('CAMISETA ESTAMPADA', 'GOLA V', 'M', 'M', 'ADULTO',13 , 20),
	('CAMISETA ESTAMPADA', 'GOLA V', 'G', 'M', 'ADULTO',13 , 20),
	('CAMISETA ESTAMPADA', 'GOLA CARECA', 'P', 'M', 'ADULTO', 13, 20),
	('CAMISETA ESTAMPADA', 'GOLA CARECA', 'M', 'M', 'ADULTO',13 , 20),
	('CAMISETA ESTAMPADA', 'GOLA CARECA', 'G', 'M', 'ADULTO',13 , 20),
	('CAMISETA ESTAMPADA', 'GOLA V', 'P', 'M', 'INFANTIL',13 , 20),
	('CAMISETA ESTAMPADA', 'GOLA V', 'M', 'M', 'INFANTIL',13 , 20),
	('CAMISETA ESTAMPADA', 'GOLA V', 'G', 'M', 'INFANTIL', 13, 20),
	('CAMISETA ESTAMPADA', 'GOLA CARECA', 'P', 'M', 'INFANTIL',13 , 20),
	('CAMISETA ESTAMPADA', 'GOLA CARECA', 'M', 'M', 'INFANTIL',13 , 20),
	('CAMISETA ESTAMPADA', 'GOLA CARECA', 'G', 'M', 'INFANTIL',13 , 20),
	('CAMISA POLO', 'CLASSIC', 'P', 'M', 'ADULTO',13 , 20),
	('CAMISA POLO', 'CLASSIC', 'M', 'M', 'ADULTO',13 , 20),
	('CAMISA POLO', 'CLASSIC', 'G', 'M', 'ADULTO', 13, 20),
	('CAMISA POLO', 'CLASSIC', 'P', 'M', 'INFANTIL',13 , 20),
	('CAMISA POLO', 'CLASSIC', 'M', 'M', 'INFANTIL',13 , 20),
	('CAMISA POLO', 'CLASSIC', 'G', 'M', 'INFANTIL',13 , 20),
	('VESTIDO LISO', 'CURTO C/ MANGA', 'P', 'F', 'ADULTO',13, 20),
	('VESTIDO LISO', 'CURTO C/ MANGA', 'M', 'F', 'ADULTO',13, 20),
	('VESTIDO LISO', 'CURTO C/ MANGA', 'G', 'F', 'ADULTO',13, 20),
	('VESTIDO LISO', 'CURTO S/ MANGA', 'P', 'F', 'ADULTO',9 , 20),
	('VESTIDO LISO', 'CURTO S/ MANGA', 'M', 'F', 'ADULTO',9 , 20),
	('VESTIDO LISO', 'CURTO S/ MANGA', 'G', 'F', 'ADULTO',9 , 20),
	('VESTIDO LISO', 'LONGO C/ MANGA', 'P', 'F', 'ADULTO',9 , 20),
	('VESTIDO LISO', 'LONGO C/ MANGA', 'M', 'F', 'ADULTO',9 , 20),
	('VESTIDO LISO', 'LONGO C/ MANGA', 'G', 'F', 'ADULTO',9 , 20),
	('VESTIDO LISO', 'LONGO S/ MANGA', 'P', 'F', 'ADULTO',9 , 20),
	('VESTIDO LISO', 'LONGO S/ MANGA', 'M', 'F', 'ADULTO',9 , 20),
	('VESTIDO LISO', 'LONGO S/ MANGA', 'G', 'F', 'ADULTO',9 , 20),
    ('VESTIDO ESTAMPADO', 'CURTO C/ MANGA', 'P', 'F', 'ADULTO', 9, 20),
	('VESTIDO ESTAMPADO', 'CURTO C/ MANGA', 'M', 'F', 'ADULTO', 9, 20),
	('VESTIDO ESTAMPADO', 'CURTO C/ MANGA', 'G', 'F', 'ADULTO',9, 20),
	('VESTIDO ESTAMPADO', 'CURTO S/ MANGA', 'P', 'F', 'ADULTO',9, 20),
	('VESTIDO ESTAMPADO', 'CURTO S/ MANGA', 'M', 'F', 'ADULTO',9, 20),
	('VESTIDO ESTAMPADO', 'CURTO S/ MANGA', 'G', 'F', 'ADULTO',10 , 20),
	('VESTIDO ESTAMPADO', 'LONGO C/ MANGA', 'P', 'F', 'ADULTO',10 , 20),
	('VESTIDO ESTAMPADO', 'LONGO C/ MANGA', 'M', 'F', 'ADULTO',10 , 20),
	('VESTIDO ESTAMPADO', 'LONGO C/ MANGA', 'G', 'F', 'ADULTO',10 , 20),
	('VESTIDO ESTAMPADO', 'LONGO S/ MANGA', 'P', 'F', 'ADULTO',10 , 20),
	('VESTIDO ESTAMPADO', 'LONGO S/ MANGA', 'M', 'F', 'ADULTO',10 , 20),
	('VESTIDO ESTAMPADO', 'LONGO S/ MANGA', 'G', 'F', 'ADULTO',10 , 20),
	( 'SHORTS', 'JEANS', '34', 'F', 'ADULTO',8 , 20),
	( 'SHORTS', 'JEANS', '36', 'F', 'ADULTO',8 , 20),
	( 'SHORTS', 'JEANS', '38', 'F', 'ADULTO',8 , 20),
	( 'SHORTS', 'JEANS', '40', 'F', 'ADULTO',8 , 20),
	( 'SHORTS', 'JEANS', '42', 'F', 'ADULTO',8 , 20);
  
/***************************************************************************************/
-- CRIANDO TABELA DE MOVIMENTO
DROP TABLE IF EXISTS MOVIMENTO;

CREATE TABLE MOVIMENTO
 (
  COD_MOVIMENTO INT NOT NULL AUTO_INCREMENT ,
  DATA_MOVIMENTO DATE,
  COD_PRODUTO INT ,
  COD_FORNECEDOR INT ,
  CARTAO_USUARIO INT ,
  ENTRADA_PRODUTO VARCHAR (5) ,
  SAIDA_PRODUTO VARCHAR (5) ,
  QUANTIDADE_PRODUTO INT NOT NULL,  
  
  PRIMARY KEY	(COD_MOVIMENTO ),
  FOREIGN KEY (COD_FORNECEDOR)      REFERENCES FORNECEDOR		(COD_FORNECEDOR ),
  FOREIGN KEY (COD_PRODUTO)         REFERENCES PRODUTO     		(COD_PRODUTO),
   FOREIGN KEY (CARTAO_USUARIO)		REFERENCES USUARIO			(CARTAO_USUARIO)

	);
INSERT INTO MOVIMENTO
	( DATA_MOVIMENTO, COD_FORNECEDOR, CARTAO_USUARIO, ENTRADA_PRODUTO, SAIDA_PRODUTO, QUANTIDADE_PRODUTO
	)
	VALUES
	('2021-03-01', '10','1322','2', '','20'),
    ('2021-03-02', '10','1322','2','', '16');


SELECT * FROM USUARIO;
SELECT * FROM FORNECEDOR;
SELECT * FROM PRODUTO ;
SELECT *    FROM MOVIMENTO;
